### ISSUE TITLE
CPT ?

### ISSUE THREAD

**Issue by daveit** [joshuaiz/plate-for-gatsby#1]
Thanks for this, looks interesting.
I'm very new to React & Gatsby, but starting to learn.
I'm a WordPress developer and wondered if this will work with Custom Post Types ?
This would be something like the WordPress WooCommerce products for example, or a specific CPT for a clients site.
I see mention of ACF when looking through the docs and articles on Gatsby/WordPress, but not a lot on CPT's
Thanks again...

**Comment by joshuaiz** [comment]
This will work with Custom Post Types as long as the `show_in_rest` parameter is set to `true` in your CPT declaration. See here: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-rest-api-support-for-custom-content-types/

Both for ACF fields and for CPT's you'll have to add your own queries but that's no different than adding your `get_field();` calls or a `WP_Query` for your CPT.

For WooCommerce `product` posts they should be queried by default although I'm not sure how those will be returned from the REST API. 

The `gatsby-source-wordpress` Gatsby plugin uses GraphQL internally but queries the WP Rest API from your WordPress install so theoretically anything that is exposed in the REST API you could pull in with Plate for Gatsby.

**Comment by daveit** [comment]
Thanks for getting back promptly  -I'll investigate your feedback...
Regards, Dave
