### ISSUE TITLE
GraphQL - Unknown field 'tags' on type 'wordpress__POST'

### ISSUE THREAD

**Issue by joniler** [joshuaiz/plate-for-gatsby#2]
Getting this failed to compile error after linking in my WP site. Any thoughts on what could be causing it to not be able to find these 'tags' & 'featured_media'?

`GraphQL Error There was an error while compiling your site's GraphQL queries.
  Error: RelayParser: Encountered 3 error(s):
- Unknown field 'tags' on type 'wordpress__POST'. Source: document `usersJonDevProjectsIlerIoSrcTemplatesPostwithsidebarJs1719491415` file: `GraphQL request`
  
  GraphQL request (17:13)
  16:             }
  17:             tags {
                  ^
  18:                 name
  
- Unknown field 'tags' on type 'wordpress__POST'. Source: document `usersJonDevProjectsIlerIoSrcTemplatesPostJs1719491415` file: `GraphQL request`
  
  GraphQL request (17:13)
  16:             }
  17:             tags {
                  ^
  18:                 name
  
- Unknown field 'featured_media' on type 'wordpress__PAGE'. Source: document `usersJonDevProjectsIlerIoSrcTemplatesPageJs3125445848` file: `GraphQL request`
  
  GraphQL request (11:13)
  10:             date(formatString: "MMMM DD, YYYY")
  11:             featured_media {
                  ^
  12:                 source_url`

**Comment by joshuaiz** [comment]
Do you have tags set in the `includedRoutes` in `gatsby-config.js` like this?

```javascript
//...
includedRoutes: [
          "**/*/*/categories",
          "**/*/*/posts",
          "**/*/*/pages",
          "**/*/*/media",
          "**/*/*/tags",
          "**/*/*/taxonomies",
          "**/*/*/users",
          "**/*/*/menus",
        ],
```

Beyond that, do you have tags and/or featured media (Feature Image) for every post or page that you are querying? If you don't, you'll need to add a conditional to show that section only if those exist and return `null` if not or you might get that error.

Can you post your whole queries and which file(s) you are calling them from?

**Comment by joniler** [comment]
I was just using the default queries against a brand new, fresh WP install. The only thing I've changed really in terms of connectivity settings is the source URL in gatsby-config.js. Shouldn't I at least be getting output using these default queries? Or have I missed something? Let me know! :)

**Comment by joshuaiz** [comment]
Are you using `gatsby build` or `gatsby develop`?

And what is this: `usersJonDevProjectsIlerIoSrcTemplatesPostwithsidebarJs1719491415`?

Is the site you're grabbing from local? Is it in a subdirectory or something else weird?

Just tried the starter with the default demo url and it is still building.

**Comment by joniler** [comment]
I actually have no idea what that is, it was automatically generated somewhere. As I said, the only thing i changed in the config was the WP source. I am using `gatsby develop`. The only thing in terms of the actual components I've changed is the default template. I just removed the starter page text and spat out a few new components that I built. It would be interesting to figure out where the hell that was generated and why. 😜

EDIT: I figured out what it's generating that based upon! That is where the project lives on my hard drive, and it's saying that the problem lies within that particular template file somehow I think... Maybe that's the ticket to figuring this out.

**Comment by joshuaiz** [comment]
So you are using a local site as the base, yes? Are you running LOCAL by Flywheel or something else? 

Anything strange in your install: in a subdirectory? not regular permalinks? anything else you can think of?

**Comment by joniler** [comment]
No, the WP site is actually hosted live on the internet at wp.iler.io actually, so in theory it should be able to contact everything to get data just fine... No custom permalinks either. Very strange.

**Comment by joshuaiz** [comment]
Can you give send me the admin login/password to your site? I can look around and see if anything is amiss. Hit me on slack.

**Comment by joshuaiz** [comment]
We got this sorted: the permalinks were set to 'Day and name' instead of 'Post name'. 

For anyone else, permalinks must be set to 'Post name' for the `gatsby-source-wordpress` plugin and this starter to work!

**Comment by joniler** [comment]
Also note: If you're not using featured images on all pages, remove it from your page query. If everything doesn't have a featured image, it will throw an error. Only include that part of the query if you are utilizing it.

Thanks to @joshuaiz for the thorough help and support!

**Comment by joshuaiz** [comment]
I should clarify that if you have featured images on some but not all pages, you'll need to add a conditional in your template so something like:

```javascript
{page.featured_media && page.featured_media.sourceUrl ? (
    <div className="featured-image">
        <img
            src={page.featured_media.sourceUrl}
            alt={page.featured_media.alt_text}
        />
    </div>
) : null}
```

Otherwise Gatsby gets upset. So either make sure you have featured images for all pages and/or posts if you are going to query and display them or include a conditional.

**Comment by 3gzon** [comment]
;elv;lmv;
